services:
  backend:
    build: ./backend
    container_name: cbmih-backend
    restart: unless-stopped
    env_file: .env
    volumes:
      - app-data:/app/data
    environment:
      - DATA_DIR=/app/data
    networks:
      - internal
      - nginx-proxy

  frontend:
    build: ./frontend
    container_name: cbmih-frontend
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - internal
      - nginx-proxy

volumes:
  app-data:

networks:
  internal:
  nginx-proxy:
    external: true
